name: Invitation Action

on:
  issues:
    types: [labeled]

jobs:
  automate_invite:
    runs-on: ubuntu-latest

    steps:
      - name: Invite-on-label
        uses: vj-abigo/invite-on-label@v1.4
        with:
          organization: DevCrafta-Team
          label: ✉️ github-invitation
          repo-token: ${{ secrets.REPO_GITHUB_TOKEN }}
          comment: "<h1><b>Welcome to DevCrafta Team!</b></h1><br>Please check your mail to accept the invitation sent by GitHub! 🤖<br><h1>About us</h1>💻 Great to have you in our community  <br>✨Looking forward to your valuable contributions! <br>🤓 You can also check our community ✨ [DevCrafta Team](https://github.com/DevCrafta-Team)
</a><br>💜 You can also share our community with other folks who want to learn about development, tech, and contribute together and with us 👉💜👈"
        env:
          INVITE_TOKEN: ${{ secrets.INVITE_ORG_TOKEN }}
